-- ==============================================================================
-- Supabase Schema Update for 260903_VIBE (Schedules & Assignee)
-- ==============================================================================

-- 1. todos 테이블에 담당자(assignee) 컬럼 추가
ALTER TABLE public.todos ADD COLUMN IF NOT EXISTS assignee TEXT DEFAULT '';

-- 2. 달력 전용 일정(schedules) 테이블 생성
CREATE TABLE IF NOT EXISTS public.schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    start_date TEXT NOT NULL,       -- YYYY-MM-DD
    end_date TEXT,                  -- YYYY-MM-DD (기간 일정 지원)
    start_time TEXT DEFAULT '',     -- HH:MM (시간 지정 시)
    is_all_day INTEGER DEFAULT 1,   -- 1: 종일, 0: 시간 지정
    location TEXT DEFAULT '',       -- 장소/회의실/링크
    color TEXT DEFAULT '#6366f1',   -- 캘린더 칩 색상
    category TEXT DEFAULT '회의',   -- 회의, 약속, 외근, 기념일, 행사 등
    created_at TEXT NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

-- 3. Row Level Security (RLS) 활성화
ALTER TABLE public.schedules ENABLE ROW LEVEL SECURITY;

-- 4. RLS 정책 설정 (익명/공개 접근 허용)
DROP POLICY IF EXISTS "Allow public read schedules" ON public.schedules;
CREATE POLICY "Allow public read schedules" ON public.schedules FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert schedules" ON public.schedules;
CREATE POLICY "Allow public insert schedules" ON public.schedules FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update schedules" ON public.schedules;
CREATE POLICY "Allow public update schedules" ON public.schedules FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete schedules" ON public.schedules;
CREATE POLICY "Allow public delete schedules" ON public.schedules FOR DELETE USING (true);

-- 5. 샘플 일정 데이터 추가
INSERT INTO public.schedules (title, description, start_date, end_date, start_time, is_all_day, location, color, category, created_at, updated_at)
VALUES 
    ('팀 주간 스프린트 킥오프', '신규 스프린트 목표 및 태스크 분배', to_char(now(), 'YYYY-MM-DD'), to_char(now(), 'YYYY-MM-DD'), '14:00', 0, '대회의실 A', '#6366f1', '회의', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('고객사 미팅 및 제품 데모', 'VIBE 프로젝트 시연', to_char(now() + interval '2 days', 'YYYY-MM-DD'), to_char(now() + interval '2 days', 'YYYY-MM-DD'), '16:30', 0, '온라인 줌(Zoom)', '#06b6d4', '약속', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('팀 테크 워크샵', '최신 AI 에이전트 기술 동향 공유', to_char(now() + interval '5 days', 'YYYY-MM-DD'), to_char(now() + interval '5 days', 'YYYY-MM-DD'), '', 1, '본사 타운홀', '#8b5cf6', '행사', to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
ON CONFLICT DO NOTHING;
