-- ==============================================================================
-- Supabase Schema for 260903_VIBE (TaskFlow Todo Web App)
-- ==============================================================================

-- 1. Create todos table
CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    category TEXT DEFAULT '일반',
    priority TEXT DEFAULT 'medium',
    due_date TEXT,
    completed INTEGER DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS'),
    updated_at TEXT NOT NULL DEFAULT to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies for Public Access (anon key)
DROP POLICY IF EXISTS "Allow public read access" ON public.todos;
CREATE POLICY "Allow public read access" ON public.todos FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert access" ON public.todos;
CREATE POLICY "Allow public insert access" ON public.todos FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update access" ON public.todos;
CREATE POLICY "Allow public update access" ON public.todos FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete access" ON public.todos;
CREATE POLICY "Allow public delete access" ON public.todos FOR DELETE USING (true);

-- 4. Insert Initial Sample Tasks
INSERT INTO public.todos (title, description, category, priority, due_date, completed, created_at, updated_at)
VALUES 
    ('Supabase 클라우드 데이터베이스 연동', 'PostgreSQL DB와 Vercel Serverless Function 실시간 연동하기', '개발', 'high', to_char(now(), 'YYYY-MM-DD'), 1, to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('팀 주간 스프린트 회의 준비', '지난 스프린트 성과 공유 및 신규 기능 로드맵 발표 자료 작성', '업무', 'medium', to_char(now(), 'YYYY-MM-DD'), 0, to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS')),
    ('도서 읽기: 파이썬 클린코드', '매일 30분씩 읽고 핵심 디자인 패턴 정리하기', '자기계발', 'low', null, 0, to_char(now(), 'YYYY-MM-DD HH24:MI:SS'), to_char(now(), 'YYYY-MM-DD HH24:MI:SS'))
ON CONFLICT DO NOTHING;
